### ISSUE TITLE
Make auto-generated docs really automatic (50 cow points)

### ISSUE THREAD

**Issue by brifordwylie** [SuperCowPowers/old-workbench-archived#128]
Right now the class/module documentation has to be invoked manually ($tox) but since Travis it doing it anyway, why can't something kewl happen and those files can just be picked my by ReadTheDocs

**Comment by iamkhush** [comment]
So the autodoc module is already doing that.

The concept here is , when RTD is builds a version, it runs sphinx-build -b html ./ _build/html, ( this is equivalent of make html) which infact reads the modules as directed by autodoc directives ( like automodule ). So, simply , adding these directives make the auto-generated documents.

Closing.

**Comment by brifordwylie** [comment]
Really?  Super neato!  So I have a few questions... in order to rebuild the docs on my local machine.. do I just run 'tox' and it will re-generate all the *.rst files under docs?  Is this in master?

**Comment by iamkhush** [comment]
Yeah, in tox you have the sphinx build and autodoc command  (https://github.com/SuperCowPowers/workbench/blob/master/tox.ini#L35) .

It is in master.
