### ISSUE TITLE
Just some small cleanup on new mozilla theme (50 cow points)

### ISSUE THREAD

**Issue by brifordwylie** [SuperCowPowers/old-workbench-archived#141]
The theme looks really nice, there are a few things that need to be fixed

1) Clean up the conf.py file when you get a chance...
2) The big 'Mozilla' tab on the right top... change it to Workbench and have it point to the workbench github page.
3) When I click on the sections on the left side bar, I don't see them expand out the sub-sections (like the sphinx theme does). Need to fix this.
4) You can see from the screens shots below that the sphinx theme does a WAY better job on the API/docstrings... so perhaps we can copy some of that CSS over to the Mozilla theme.
![screen shot 2014-06-29 at 7 20 51 pm](https://cloud.githubusercontent.com/assets/4806709/3425068/e82e22b0-fff4-11e3-92d9-a10e06a84d5b.png)
![screen shot 2014-06-29 at 7 21 03 pm](https://cloud.githubusercontent.com/assets/4806709/3425069/e9fcca6a-fff4-11e3-8c96-478fceade55b.png)

**Comment by iamkhush** [comment]
Mozilla theme isnt showing on RTD.  Need to fix that as well.

**Comment by brifordwylie** [comment]
Everything looks good except the CSS on the API code (copy what the sphinx theme does) see screenshot above.

**Comment by brifordwylie** [comment]
Looks awesome. Closing the issue...
