### ISSUE TITLE
Look into ReadTheDocs for documentation (25 cow points)

### ISSUE THREAD

**Issue by brifordwylie** [SuperCowPowers/old-workbench-archived#17]
https://readthedocs.org/

**Comment by brifordwylie** [comment]
Set up the workbench repo to have super nice documentation (https://readthedocs.org/). We already have it setup, just need to do some reorg, move the material that's currently in the readme's into the docs/ directory, organize it and make sure all the classes are automatically included in the class/API docs.

**Comment by iamkhush** [comment]
The docs can be seen at http://workbench.readthedocs.org/en/setup_rtfd/.

**Comment by iamkhush** [comment]
Merged with Pull https://github.com/SuperCowPowers/workbench/pull/116
