### ISSUE TITLE
Figure out how to silence 'nonlocal image URI found' when building docs (10 cow points)

### ISSUE THREAD

**Issue by brifordwylie** [SuperCowPowers/old-workbench-archived#172]
There must be a sphinx option you can throw into tox.ini (kinda like the pytest options that are there). The problem is that I/we start ignore real issues in the docs if we get spammed by this warning all the time.

**Comment by iamkhush** [comment]
Issue has been discussed here - https://groups.google.com/forum/#!topic/sphinx-users/GNx7PVXoZIU. and a neat solution is also given here http://stackoverflow.com/questions/12772927/specifying-an-online-image-in-sphinx-restructuredtext-format.

**Comment by brifordwylie** [comment]
yep, looks good.. now we can see the 'real' warnings that are important.
