### ISSUE TITLE
Make the PyPI page/docs look good (75 cow points)

### ISSUE THREAD

**Issue by brifordwylie** [SuperCowPowers/old-workbench-archived#185]
Okay, we're starting our PyPI 'push'. So the project is setup and you can push to PyPI just by following our new checklist (see https://gist.github.com/brifordwylie/726ece89c9f28b9bd8dd) note this needs updating and I'll see if I can move it to the workbench repo in some way...

But getting to the point the workbench page on PyPI looks super bad right now, need to make it look 'professional' https://pypi.python.org/pypi/workbench

**Comment by iamkhush** [comment]
PyPy calls rst2html.py command with a --no-raw flag. It means that the  "raw" directive is disabled.
Now, this is madness. I added raw directive to remove the error on rtd for no local image found.

Anyways, for now , I have made a new file README_PYPY.rst, and linked it into setup.py, until I find a better soluton.

**Comment by brifordwylie** [comment]
This thread seems useful.. http://stackoverflow.com/questions/16367770/my-rst-readme-is-not-formatted-on-pypi-python-org
