### ISSUE TITLE
Make a Workbench 'Docker' container (400 cow points)

### ISSUE THREAD

**Issue by brifordwylie** [SuperCowPowers/old-workbench-archived#280]
Docker seems kewl.. check it out and make a Workbench docker container.

**Comment by brifordwylie** [comment]
This might come in handy super quick, so bumping this up in priority.

**Comment by brifordwylie** [comment]
Moving to 0.4

**Comment by iamkhush** [comment]
I have made a docker image . Uploaded to hub with at iamkhush/workbench.
I have installed the latest version of workbench on it.

**Comment by brifordwylie** [comment]
Thanks for getting this started Ankush, I've done some deep digging on how to get all the dependencies setup etc. The Dockerfile is now housed at https://github.com/SuperCowPowers/workbench-docker. Also complete, going to flip this issue over to me.

**Comment by brifordwylie** [comment]
okay first version of this is done. It works but is very bloated.
