### ISSUE TITLE
Neo4j graph to D3 vis

### ISSUE THREAD

**Issue by brifordwylie** [SuperCowPowers/old-workbench-archived#37]
We would like to have a path from Neo4j graph to D3 vis. Probably lots of examples but here's one I found http://maxdemarzi.com/2012/02/02/graph-visualization-and-neo4j-part-three/.

**Comment by Analect** [comment]
@brifordwylie , your latest notebook (PCAP to Graph) is featured in Python Weekly FYI http://eepurl.com/WeGqr
Your notebooks are a font of learning!  Does that Neo4j chart render directly in the notebook ... or is that just a screenshot?  Did you have to modify the grass file to get all those annotations on the neo4j graph, including on the edges?
I recommend you look at this recent presentation (https://www.youtube.com/watch?v=NzX7DDRkecU) from Jake Vanderplas at an OpenVis conference ... he appears to have done alot of work to bring D3 interactivity to matplotlib charts in the notebook via his http://mpld3.github.io/ project.
Best. Colum

**Comment by brifordwylie** [comment]
Hey, super neat!  Thanks for the shout out.

Yes the image is just a screen shot from the Neo4j browser. I like mpld3
quite a bit I've used it in some of my other notebooks.

The workbench repository has a grass file in
workbench/utils/graphstyle.grass that you can upload to the Neo4j browser.

We're looking for contributors so let me know if you (or your friends)
would like to poke around with workbench. :)

Best regards,
-bri

On Thu, Jun 5, 2014 at 11:07 AM, Analect notifications@github.com wrote:

> @brifordwylie https://github.com/brifordwylie , your latest notebook
> (PCAP to Graph) is featured in Python Weekly FYI http://eepurl.com/WeGqr
> Your notebooks are a font of learning! Does that Neo4j chart render
> directly in the notebook ... or is that just a screenshot? Did you have to
> modify the grass file to get all those annotations on the neo4j graph,
> including on the edges?
> I recommend you look at this recent presentation (
> https://www.youtube.com/watch?v=NzX7DDRkecU) from Jake Vanderplas at an
> OpenVis conference ... he appears to have done alot of work to bring D3
> interactivity to matplotlib charts in the notebook via his
> http://mpld3.github.io/ project.
> Best. Colum
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/SuperCowPowers/workbench/issues/37#issuecomment-45246732
> .

## 

Brian Wylie
www.supercowpowers.com
Skype: briford.wylie
Phone: (505) 206-4295

**Comment by brifordwylie** [comment]
Actually since we're moving to NetworkX as our 'native' graph format I'll probably close this issue. We're still going to use Neo4j, we will use NeoNx (https://github.com/ducky427/neonx) to push NetworkX graphs into Neo4j.
